{{- if and (.Values.certManager) (.Values.certManager.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-pca-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.chartPath }}/aws-pca-issuer
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      # Sane defaults for aws-pca-issuer
      valueFiles:
      - values.yaml
      # Dynamic values passed from terraform
      values: |
        aws-pca-issuer:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.accountId }}:role/{{ .Values.clusterName }}-aws-pca-issuer"
        {{- toYaml .Values | nindent 10 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end -}}
